const notes = [
    { id: 1, topic: "Computer Science", note: "Time complexity of binary search is O(log n)." },
    { id: 2, topic: "Computer Science", note: "Inheritance enables code reuse in object-oriented programming." },
    { id: 3, topic: "Computer Science", note: "The OSI model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application." },
    { id: 4, topic: "Computer Science", note: "Recursion involves a function calling itself to solve subproblems." },
    { id: 5, topic: "Computer Science", note: "A hash table provides average O(1) time complexity for insert and lookup." },
    { id: 6, topic: "Computer Science", note: "Depth-First Search uses a stack; Breadth-First Search uses a queue." },
    { id: 7, topic: "Computer Science", note: "A deadlock occurs when processes wait for each other indefinitely." },
    { id: 8, topic: "Computer Science", note: "Big-O notation describes the worst-case performance of an algorithm." },
    { id: 9, topic: "Computer Science", note: "CPU cache speeds up memory access by storing frequently used data." },
    { id: 10, topic: "Computer Science", note: "A race condition occurs when the outcome depends on execution order." },
    { id: 11, topic: "Computer Science", note: "A compiler translates source code into machine code." },
    { id: 12, topic: "Computer Science", note: "The Turing Machine is a theoretical model of computation." },
    { id: 13, topic: "Computer Science", note: "Dijkstra's algorithm finds the shortest path in a weighted graph." },
    { id: 14, topic: "Computer Science", note: "P vs NP is an unsolved question in computer science theory." },
    { id: 15, topic: "Computer Science", note: "A linked list is a linear data structure with nodes pointing to the next." },
    { id: 16, topic: "Frontend Development", note: "The DOM represents the structure of a web page as a tree of nodes." },
    { id: 17, topic: "Frontend Development", note: "React uses a virtual DOM for efficient UI updates." },
    { id: 18, topic: "Frontend Development", note: "JSX is a syntax extension that allows HTML-like code in JavaScript." },
    { id: 19, topic: "Frontend Development", note: "In React, components can be functional or class-based." },
    { id: 20, topic: "Frontend Development", note: "useState is a React Hook for managing component state." },
    { id: 21, topic: "Frontend Development", note: "useEffect runs side effects in functional components." },
    { id: 22, topic: "Frontend Development", note: "Props are read-only data passed from parent to child components." },
    { id: 23, topic: "Frontend Development", note: "CSS Flexbox makes it easy to align items in one dimension." },
    { id: 24, topic: "Frontend Development", note: "The box model consists of content, padding, border, and margin." },
    { id: 25, topic: "Frontend Development", note: "Media queries allow responsive design based on screen size." },
    { id: 26, topic: "Frontend Development", note: "Tailwind CSS is a utility-first CSS framework." },
    { id: 27, topic: "Frontend Development", note: "Component libraries like Material UI speed up development." },
    { id: 28, topic: "Frontend Development", note: "Next.js enables server-side rendering for React apps." },
    { id: 29, topic: "Frontend Development", note: "React context provides a way to pass data without prop drilling." },
    { id: 30, topic: "Frontend Development", note: "Controlled components bind input elements to React state." },
    { id: 31, topic: "Frontend Development", note: "TypeScript adds static typing to JavaScript." },
    { id: 32, topic: "Frontend Development", note: "A debounce function limits how often a callback is fired." },
    { id: 33, topic: "Frontend Development", note: "Webpack bundles modules and assets into a single file." },
    { id: 34, topic: "Frontend Development", note: "useRef stores mutable values that persist across renders." },
    { id: 35, topic: "Frontend Development", note: "Styled Components allow writing CSS-in-JS." },
    { id: 36, topic: "Web Development", note: "HTTP is a stateless protocol for client-server communication." },
    { id: 37, topic: "Web Development", note: "RESTful APIs use HTTP methods to manipulate resources." },
    { id: 38, topic: "Web Development", note: "JSON is a lightweight format for data exchange." },
    { id: 39, topic: "Web Development", note: "CORS is a security feature to restrict cross-origin requests." },
    { id: 40, topic: "Web Development", note: "JWTs are used for stateless authentication." },
    { id: 41, topic: "Web Development", note: "A CDN delivers content from the server closest to the user." },
    { id: 42, topic: "Web Development", note: "HTTPS encrypts data using SSL/TLS." },
    { id: 43, topic: "Web Development", note: "SSR renders pages on the server for faster first paint." },
    { id: 44, topic: "Web Development", note: "CRUD operations stand for Create, Read, Update, Delete." },
    { id: 45, topic: "Web Development", note: "Local storage allows storing data in the browser." },
    { id: 46, topic: "Web Development", note: "OAuth 2.0 is a protocol for delegated authorization." },
    { id: 47, topic: "Web Development", note: "WebSockets provide real-time two-way communication." },
    { id: 48, topic: "Web Development", note: "A service worker enables offline functionality in web apps." },
    { id: 49, topic: "Web Development", note: "GraphQL is a query language for APIs." },
    { id: 50, topic: "Web Development", note: "Lighthouse audits site performance, accessibility, and SEO." },
    { id: 35, topic: "Backend Development", note: "Express.js is a minimalist web framework for Node.js." },
    { id: 36, topic: "Backend Development", note: "Middleware functions in Express can modify requests and responses." },
    { id: 37, topic: "Backend Development", note: "Node.js uses an event-driven, non-blocking I/O model." },
    { id: 38, topic: "Backend Development", note: "Environment variables are stored in a .env file using dotenv." },
    { id: 39, topic: "Backend Development", note: "JWTs are commonly used for stateless authentication." },
    { id: 40, topic: "Backend Development", note: "Bcrypt is used to securely hash passwords." },
    { id: 41, topic: "Backend Development", note: "RESTful APIs use HTTP methods to perform CRUD operations." },
    { id: 42, topic: "Backend Development", note: "CORS controls which origins can access server resources." },
    { id: 43, topic: "Backend Development", note: "MVC stands for Model-View-Controller architecture." },
    { id: 44, topic: "Backend Development", note: "The 500 status code indicates a server-side error." },
    { id: 45, topic: "Databases", note: "SQL is used to query and manipulate relational databases." },
    { id: 46, topic: "Databases", note: "A primary key uniquely identifies each row in a table." },
    { id: 47, topic: "Databases", note: "Indexes speed up SELECT queries but slow down INSERTs." },
    { id: 48, topic: "Databases", note: "ACID stands for Atomicity, Consistency, Isolation, Durability." },
    { id: 49, topic: "Databases", note: "MongoDB is a NoSQL database that stores documents as BSON." },
    { id: 50, topic: "Databases", note: "Joins combine rows from two or more tables based on a related column." },
    { id: 51, topic: "Databases", note: "Normalization reduces data redundancy by splitting tables." },
    { id: 52, topic: "Databases", note: "Transactions allow multiple queries to execute as a single unit." },
    { id: 53, topic: "Databases", note: "A foreign key links rows in one table to another." },
    { id: 54, topic: "Databases", note: "Supabase is an open-source alternative to Firebase built on Postgres." },
    { id: 55, topic: "APIs", note: "GraphQL allows clients to request exactly the data they need." },
    { id: 56, topic: "APIs", note: "An API key is a token used to authenticate requests to an API." },
    { id: 57, topic: "APIs", note: "Rate limiting helps prevent abuse by capping API requests per user." },
    { id: 58, topic: "APIs", note: "Webhooks send data to other services when an event occurs." },
    { id: 59, topic: "APIs", note: "gRPC is a high-performance, open-source RPC framework by Google." },
    { id: 60, topic: "DevOps", note: "Docker packages applications with all dependencies into containers." },
    { id: 61, topic: "DevOps", note: "Kubernetes automates container orchestration and scaling." },
    { id: 62, topic: "DevOps", note: "CI/CD stands for Continuous Integration and Continuous Deployment." },
    { id: 63, topic: "DevOps", note: "NGINX can be used as a reverse proxy and load balancer." },
    { id: 64, topic: "DevOps", note: "YAML files are commonly used to define CI/CD pipelines." },
    { id: 65, topic: "DevOps", note: "GitHub Actions enable workflow automation on code events." },
    { id: 66, topic: "DevOps", note: "A VPS is a virtual server that gives root access to deploy apps." },
    { id: 67, topic: "DevOps", note: "Monitoring tools like Prometheus help track application health." },
    { id: 68, topic: "DevOps", note: "SSL certificates encrypt data exchanged over HTTPS." },
    { id: 69, topic: "DevOps", note: "Systemd services can auto-start your app on server boot." },
    { id: 70, topic: "AI/Machine Learning", note: "A neural network is inspired by the structure of the human brain." },
    { id: 71, topic: "AI/Machine Learning", note: "Supervised learning uses labeled data for training." },
    { id: 72, topic: "AI/Machine Learning", note: "Overfitting happens when a model performs well on training data but poorly on new data." },
    { id: 73, topic: "AI/Machine Learning", note: "Gradient descent minimizes the error in a model by updating weights." },
    { id: 74, topic: "AI/Machine Learning", note: "Embeddings convert text or images into vector representations." },
    { id: 75, topic: "AI/Machine Learning", note: "GPT stands for Generative Pre-trained Transformer." },
    { id: 76, topic: "AI/Machine Learning", note: "The ReAct strategy combines reasoning and action for agents." },
    { id: 77, topic: "AI/Machine Learning", note: "Open source models like Mistral and LLaMA can run locally." },
    { id: 78, topic: "AI/Machine Learning", note: "Vector databases like Pinecone or Supabase store embeddings for similarity search." },
    { id: 79, topic: "AI/Machine Learning", note: "Fine-tuning adjusts a pre-trained model for specific tasks." },
    { id: 80, topic: "AI/Machine Learning", note: "Prompt engineering helps guide LLM output effectively." }
];

module.exports = notes;